### ISSUE TITLE
kubernetes-aws-python fails to run in default configuration

### ISSUE THREAD

**Issue by Vad1mo** [pulumi/templates#501]
### What happened?

I was following the tutorial https://www.pulumi.com/templates/kubernetes/aws/ that uses the `kubernetes-aws-python` template

### Steps to reproduce

```sh
$pulumi version 
v3.51.1
```

```sh
mkdir hello-eks
cd hello-eks
pulumi new kubernetes-aws-python
pulumi up
```

I didn't make any code or config changes except setting the region to `eu-north-1`

```yaml
encryptionsalt: --redacted--
config:
  aws:region: eu-north-1
  hello-eks:desiredClusterSize: "3"
  hello-eks:eksNodeInstanceType: t2.medium
  hello-eks:maxClusterSize: "6"
  hello-eks:minClusterSize: "3"
  hello-eks:vpcNetworkCidr: 10.0.0.0/16

```

### Expected Behavior

I was expecting `pulumi up` to succeed

### Actual Behavior

```sh
+   └─ eks:index:Cluster                          eks-cluster                                    created                 
 +      ├─ eks:index:ServiceRole                   eks-cluster-eksRole                            created (9s)            
 +      │  ├─ aws:iam:Role                         eks-cluster-eksRole-role                       created (2s)            
 +      │  └─ aws:iam:RolePolicyAttachment         eks-cluster-eksRole-4b490823                   created (1s)            
 +      ├─ eks:index:ServiceRole                   eks-cluster-instanceRole                       created (10s)           
 +      │  ├─ aws:iam:Role                         eks-cluster-instanceRole-role                  created (2s)            
 +      │  ├─ aws:iam:RolePolicyAttachment         eks-cluster-instanceRole-03516f97              created (1s)            
 +      │  ├─ aws:iam:RolePolicyAttachment         eks-cluster-instanceRole-3eb088f2              created (2s)            
 +      │  └─ aws:iam:RolePolicyAttachment         eks-cluster-instanceRole-e1b295bd              created (2s)            
 +      ├─ aws:ec2:SecurityGroup                   eks-cluster-eksClusterSecurityGroup            created (2s)            
 +      ├─ eks:index:RandomSuffix                  eks-cluster-cfnStackName                       created (0.97s)         
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksClusterInternetEgressRule       created (1s)            
 +      ├─ aws:eks:Cluster                         eks-cluster-eksCluster                         created (503s)          
 +      ├─ aws:iam:InstanceProfile                 eks-cluster-instanceProfile                    created (1s)            
 +      ├─ aws:ec2:SecurityGroup                   eks-cluster-nodeSecurityGroup                  created (2s)            
 +      ├─ pulumi:providers:kubernetes             eks-cluster-eks-k8s                            created (0.47s)         
 +      ├─ eks:index:VpcCni                        eks-cluster-vpc-cni                            created (2s)            
 +      ├─ kubernetes:core/v1:ConfigMap            eks-cluster-nodeAccess                         created (0.63s)         
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksExtApiServerClusterIngressRule  created (1s)            
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksClusterIngressRule              created (1s)            
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksNodeIngressRule                 created (2s)            
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksNodeClusterIngressRule          created (2s)            
 +      ├─ aws:ec2:SecurityGroupRule               eks-cluster-eksNodeInternetEgressRule          created (3s)            
 +      ├─ aws:ec2:LaunchConfiguration             eks-cluster-nodeLaunchConfiguration            created (2s)            
 +      └─ aws:cloudformation:Stack                eks-cluster-nodes                              **creating failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (hello-eks-hello-dev):
    error: update failed
    error: TypeError: Cannot use 'in' operator to search for 'NodeGroup' in undefined
        at /snapshot/eks/bin/nodegroup.js:418:27
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:257:35
        at Generator.next (<anonymous>)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:236:12)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:190:65
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 617, in do_rpc_call
        return monitor.RegisterResource(req)
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNKNOWN
    	details = "Cannot use 'in' operator to search for 'NodeGroup' in undefined"
    	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:53944 {created_time:"2023-01-14T15:36:21.670239+01:00", grpc_status:2, grpc_message:"Cannot use \'in\' operator to search for \'NodeGroup\' in undefined"}"
    >
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/Users/vadim/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/output.py", line 172, in run
        is_known = await self._is_known
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/output.py", line 103, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 622, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/Users/vadim/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 619, in do_rpc_call
        handle_grpc_error(exn)
      File "/Users/vadim/Development/saas-factory/k8s/infra/hello-eks/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: Cannot use 'in' operator to search for 'NodeGroup' in undefined

    TypeError: Cannot use 'in' operator to search for 'NodeGroup' in undefined: TypeError: Cannot use 'in' operator to search for 'NodeGroup' in undefined
        at /snapshot/eks/bin/nodegroup.js:418:27
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:257:35
        at Generator.next (<anonymous>)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:17:12)
        at applyHelperAsync (/snapshot/eks/node_modules/@pulumi/pulumi/output.js:236:12)
        at /snapshot/eks/node_modules/@pulumi/pulumi/output.js:190:65
        at processTicksAndRejections (node:internal/process/task_queues:95:5)

  aws:cloudformation:Stack (eks-cluster-nodes):
    error: 1 error occurred:
    	* creating urn:pulumi:hello-dev::hello-eks::eks:index:Cluster$aws:cloudformation/stack:Stack::eks-cluster-nodes: 1 error occurred:
    	* error waiting for CloudFormation Stack (arn:aws:cloudformation:eu-north-1:163500494166:stack/eks-cluster-470e1c47/add84070-9418-11ed-a490-06bccd10b7de) create: failed to create CloudFormation stack, rollback requested (ROLLBACK_COMPLETE): ["The following resource(s) failed to create: [NodeGroup]. Rollback requested by user." "The requested configuration is currently not supported. Please check the documentation for supported configurations. Launching EC2 instance failed."]
```

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.27.0
awsx        1.0.1
docker      3.6.1
eks         1.0.1
kubernetes  3.23.1
python      unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in python: executable='/Users/vadim/.pyenv/shims/python3' version='3.10.6
'

Current Stack: hello-dev

Found no resources associated with hello-dev

Found no pending operations associated with hello-dev

Backend        
Name           Vady-MacFly.local
URL            s3://hv-8g-pulumi-state
User           vadim
Organizations  

Dependencies:
NAME         VERSION
pip          22.3.1
pulumi-awsx  1.0.1
pulumi-eks   1.0.1
setuptools   65.7.0
wheel        0.38.4

Pulumi locates its logs in /var/folders/v5/27sfclt13g54_qgh9kmkqf6w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Vad1mo** [comment]
I explored the issue further. Conclusion: It works `us-west-2` but not in `eu-north-1`.

**Comment by scottslowe** [comment]
@Vad1mo Thanks for filing this issue! The problem is that the `eu-north-1` region doesn't support `t2` instance types (verified using `aws ec2 describe-instance-type-offerings --region eu-north-1`). It does support `t3` instance types, and I verified that the template works as expected if you supply `t3.medium` as the EKS node instance type.

We will still take this as a bug and work on providing a fix, but I wanted to at least provide you with a workaround in the meantime.
